name: "flake check"

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:

jobs:
  eval:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        targets:
          - repo: NixOS/nixpkgs
            branch: nixos-24.05
          - repo: NixOS/nixpkgs
            branch: nixos-unstable

          - repo: NuschtOS/nuschtpkgs
            branch: nixos-24.05
          - repo: NuschtOS/nuschtpkgs
            branch: backports-24.05
          - repo: NuschtOS/nuschtpkgs
            branch: nixos-unstable

          - repo: SuperSandro2000/nixpkgs
            branch: nixos-unstable

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30

      - name: eval ${{ matrix.targets.repo }}/${{ matrix.targets.branch }}
        if: matrix.targets.repo != 'NuschtOS/nuschtpkgs' && matrix.targets.branch != 'nixos-unstable'
        run: |
          nix eval -L .#nixosConfigurations.test.config.system.build.toplevel \
            --override-input nixpkgs github:${{ matrix.targets.repo }}/${{ matrix.targets.branch }}

      - name: eval flake lock
        if: matrix.targets.repo == 'NuschtOS/nuschtpkgs' && matrix.targets.branch == 'nixos-unstable'
        run: |
          nix eval -L .#nixosConfigurations.test.config.system.build.toplevel
