name: Post compare link when flake.lock changes

permissions:
  issues: write
  pull-requests: write

on:
  pull_request:
    paths: ['flake.lock']

jobs:
  post-compare-link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: NuschtOS/flake-lock-compare-action@main
