name: "Sync template"
on:
  workflow_dispatch:
  schedule:
  - cron:  "0 0 1 * *"
jobs:
  repo-sync:
    if: github.repository != 'NuschtOS/template'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: AndreasAugustin/actions-template-sync@v2
        with:
          github_token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          source_repo_path: NuschtOS/template
