name: "Update flakes"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  update-flakes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v29
      - uses: DeterminateSystems/update-flake-lock@v24
        if: ${{ hashFiles('flake.nix') != '' }}
        with:
          # required to trigger GitHub Actions on the created PRs
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
